# Generated by Django 3.1.2 on 2020-10-02 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUserConfig',
            fields=[
                ('username', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('gravatar_id', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('range_to_look_at', models.CharField(max_length=255)),
                ('count_quota', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SlackOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('team_id', models.CharField(max_length=20)),
                ('bot_user_id', models.CharField(max_length=20)),
                ('bot_access_token', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Authorized Company Slack Account',
                'verbose_name_plural': 'Authorized Company Slack Accounts',
            },
        ),
        migrations.CreateModel(
            name='SlackUserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('slack_id', models.CharField(max_length=255)),
                ('notification_settings', models.ManyToManyField(to='github_checker.NotificationSettings')),
                ('slack_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github_checker.slackorg')),
            ],
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('watch_for_pull_requests', models.BooleanField(default=False)),
                ('notify_count_in_slack', models.BooleanField(default=False)),
                ('github_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github_checker.githubuserconfig')),
                ('slack_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github_checker.slackuserconfig')),
            ],
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(blank=True, max_length=255)),
                ('pull_id', models.IntegerField(unique=True)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(null=True)),
                ('body', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github_checker.userconfig')),
            ],
        ),
    ]
