# Generated by Django 3.1.2 on 2020-10-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_checker', '0002_auto_20201003_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='conn_configs',
            field=models.ManyToManyField(to='github_checker.ConnectionUserConfig'),
        ),
    ]
