# Generated by Django 3.1.2 on 2020-10-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_checker', '0005_auto_20201005_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuserconfig',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
