# Generated by Django 3.1.2 on 2020-10-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_checker', '0006_auto_20201005_1957'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userconfig',
            unique_together={('name', 'github_user')},
        ),
    ]
