# Generated by Django 3.1.2 on 2020-10-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_checker', '0007_auto_20201005_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackorg',
            name='team_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
