# Generated by Django 3.1.2 on 2020-10-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_count_in_slack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='watch_for_pull_requests',
            field=models.BooleanField(default=False),
        ),
    ]
